# Generated by Django 6.0.3 on 2026-03-24 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_likepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likepost',
            old_name='post',
            new_name='post_id',
        ),
    ]
